fix: [PIDM-1668] Helm dev cron job command

diff --git a/helm/values-dev.yaml b/helm/values-dev.yaml
--- a/helm/values-dev.yaml
+++ b/helm/values-dev.yaml
@@ -194,24 +194,10 @@ retry-dead-letter-cron:
   schedule: "*/5 * * * *" # Every 5 minutes
   timeZone: "Europe/Rome"
   image:
-    repository: "alpine/curl"
+    repository: "alpine"
     tag: "latest"
     pullPolicy: "Always"
-  command:
-    - "/bin/sh"
-    - "-c"
-    - >-
-      set -e;
-      BASE_URL="https://weudev.gps.internal.dev.platform.pagopa.it/gpd-rtp-service";
-      RESPONSE=$(curl -s -k ${BASE_URL}/error-messages);
-      if [ -z "$RESPONSE" ] || [ "$RESPONSE" = "[]" ]; then
-        echo "No messages to retry";
-        exit 0;
-      fi;
-      curl -s -k -X POST
-        -H "Content-Type: application/json"
-        -d "$RESPONSE"
-        ${BASE_URL}/error-messages/retry
+  command: ["/bin/bash", "-c", "set -e; BASE_URL=\"https://weudev.gps.internal.dev.platform.pagopa.it/gpd-rtp-service\"; RESPONSE=$(curl -s -k ${BASE_URL}/error-messages); if [ -z \"$RESPONSE\" ] || [ \"$RESPONSE\" = \"[]\" ]; then echo \"No messages to retry\"; exit 0; fi; curl -s -k -X POST -H \"Content-Type: application/json\" -d \"$RESPONSE\" ${BASE_URL}/error-messages/retry"]
   resources:
     requests:
       memory: "256Mi"
