test

diff --git a/.github/workflows/cd_release_deploy.yml b/.github/workflows/cd_release_deploy.yml
--- a/.github/workflows/cd_release_deploy.yml
+++ b/.github/workflows/cd_release_deploy.yml
@@ -48,118 +48,120 @@ permissions:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  setup:
-    name: Setup
-    runs-on: ubuntu-latest
-    outputs:
-      semver: ${{ steps.get_semver.outputs.semver }}
-      environment: ${{ steps.get_env.outputs.environment }}
-    steps:
-      - name: pull request rejected
-        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged != true
-        run: |
-          echo "❌ PR was closed without a merge"
-          exit 1
-
-      # Set Semvar
-      - run: echo "SEMVER=patch" >> $GITHUB_ENV
-
-      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'skip')) }}
-        run: echo "SEMVER=skip" >> $GITHUB_ENV
-
-      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'patch')) }}
-        run: echo "SEMVER=patch" >> $GITHUB_ENV
-
-      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'minor')) }}
-        run: echo "SEMVER=minor" >> $GITHUB_ENV
-
-      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'major')) }}
-        run: echo "SEMVER=major" >> $GITHUB_ENV
-
-      # force semver if dev, !=main or skip release
-      - if: ${{ inputs.version == 'new_release' }}
-        run: echo "SEMVER=minor" >> $GITHUB_ENV
-
-      - if: ${{ inputs.version == 'breaking_change' }}
-        run: echo "SEMVER=major" >> $GITHUB_ENV
-
-      - if: ${{ github.ref_name != 'main' }}
-        run: echo "SEMVER=buildNumber" >> $GITHUB_ENV
-
-      - if: ${{ inputs.version == 'skip_or_promote' }}
-        run: echo "SEMVER=skip" >> $GITHUB_ENV
-
-      - id: get_semver
-        name: Set Output
-        run: echo "semver=${{env.SEMVER}}" >> $GITHUB_OUTPUT
-
-      # Set Environment
-      - run: echo "ENVIRNOMENT=${{ inputs.environment}}" >> $GITHUB_ENV
-
-      - if: ${{ inputs.environment == null }}
-        run: echo "ENVIRNOMENT=dev" >> $GITHUB_ENV
-
-      - id: get_env
-        name: Set Output
-        run: echo "environment=${{env.ENVIRNOMENT}}" >> $GITHUB_OUTPUT
-
-  release:
-    name: Create a New Release
-    runs-on: ubuntu-latest
-    needs: [ setup ]
-    if: ${{ needs.setup.outputs.semver != 'skip' }}
-    outputs:
-      version: ${{ steps.release.outputs.version }}
-    steps:
-      - name: Make Release
-        id: release
-        uses: pagopa/github-actions-template/maven-release@38203c7599bcac41a743237ccb17c733ff9c2eee # v1.12.0
-        with:
-          semver: ${{ needs.setup.outputs.semver }}
-          github_token: ${{ secrets.BOT_TOKEN_GITHUB }}
-          beta: ${{ inputs.beta }}
-          skip_ci: true
-          prerelease: ${{  github.ref_name != 'main' }}
-          only_tag: false
-
-  image:
-    needs: [ setup, release ]
-    name: Build and Push Docker Image
-    runs-on: ubuntu-latest
-    if: ${{ needs.setup.outputs.semver != 'skip' }}
-    steps:
-      - name: Build and Push
-        id: semver
-        uses: pagopa/github-actions-template/ghcr-build-push@d91a1fd0b913c9830589be5d86cdb71c90813fae # v1.5.4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          tag: ${{ needs.release.outputs.version }}
-
-  deploy_aks:
-    name: Deploy on AKS
-    needs: [ setup, release, image ]
-    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
-    uses: ./.github/workflows/cd_deploy_with_github_runner.yml
-    with:
-      environment: ${{ needs.setup.outputs.environment }}
-    secrets: inherit
+#  setup:
+#    name: Setup
+#    runs-on: ubuntu-latest
+#    outputs:
+#      semver: ${{ steps.get_semver.outputs.semver }}
+#      environment: ${{ steps.get_env.outputs.environment }}
+#    steps:
+#      - name: pull request rejected
+#        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged != true
+#        run: |
+#          echo "❌ PR was closed without a merge"
+#          exit 1
+#
+#      # Set Semvar
+#      - run: echo "SEMVER=patch" >> $GITHUB_ENV
+#
+#      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'skip')) }}
+#        run: echo "SEMVER=skip" >> $GITHUB_ENV
+#
+#      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'patch')) }}
+#        run: echo "SEMVER=patch" >> $GITHUB_ENV
+#
+#      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'minor')) }}
+#        run: echo "SEMVER=minor" >> $GITHUB_ENV
+#
+#      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'major')) }}
+#        run: echo "SEMVER=major" >> $GITHUB_ENV
+#
+#      # force semver if dev, !=main or skip release
+#      - if: ${{ inputs.version == 'new_release' }}
+#        run: echo "SEMVER=minor" >> $GITHUB_ENV
+#
+#      - if: ${{ inputs.version == 'breaking_change' }}
+#        run: echo "SEMVER=major" >> $GITHUB_ENV
+#
+#      - if: ${{ github.ref_name != 'main' }}
+#        run: echo "SEMVER=buildNumber" >> $GITHUB_ENV
+#
+#      - if: ${{ inputs.version == 'skip_or_promote' }}
+#        run: echo "SEMVER=skip" >> $GITHUB_ENV
+#
+#      - id: get_semver
+#        name: Set Output
+#        run: echo "semver=${{env.SEMVER}}" >> $GITHUB_OUTPUT
+#
+#      # Set Environment
+#      - run: echo "ENVIRNOMENT=${{ inputs.environment}}" >> $GITHUB_ENV
+#
+#      - if: ${{ inputs.environment == null }}
+#        run: echo "ENVIRNOMENT=dev" >> $GITHUB_ENV
+#
+#      - id: get_env
+#        name: Set Output
+#        run: echo "environment=${{env.ENVIRNOMENT}}" >> $GITHUB_OUTPUT
+#
+#  release:
+#    name: Create a New Release
+#    runs-on: ubuntu-latest
+#    needs: [ setup ]
+#    if: ${{ needs.setup.outputs.semver != 'skip' }}
+#    outputs:
+#      version: ${{ steps.release.outputs.version }}
+#    steps:
+#      - name: Make Release
+#        id: release
+#        uses: pagopa/github-actions-template/maven-release@38203c7599bcac41a743237ccb17c733ff9c2eee # v1.12.0
+#        with:
+#          semver: ${{ needs.setup.outputs.semver }}
+#          github_token: ${{ secrets.BOT_TOKEN_GITHUB }}
+#          beta: ${{ inputs.beta }}
+#          skip_ci: true
+#          prerelease: ${{  github.ref_name != 'main' }}
+#          only_tag: false
+#
+#  image:
+#    needs: [ setup, release ]
+#    name: Build and Push Docker Image
+#    runs-on: ubuntu-latest
+#    if: ${{ needs.setup.outputs.semver != 'skip' }}
+#    steps:
+#      - name: Build and Push
+#        id: semver
+#        uses: pagopa/github-actions-template/ghcr-build-push@d91a1fd0b913c9830589be5d86cdb71c90813fae # v1.5.4
+#        with:
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          tag: ${{ needs.release.outputs.version }}
+#
+#  deploy_aks:
+#    name: Deploy on AKS
+#    needs: [ setup, release, image ]
+#    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
+#    uses: ./.github/workflows/cd_deploy_with_github_runner.yml
+#    with:
+#      environment: ${{ needs.setup.outputs.environment }}
+#    secrets: inherit
 
   start_consumers:
     name: Start Consumers
     runs-on: ubuntu-latest
-    needs: [ deploy_aks ]
-    if: ${{ inputs.start_consumer }}
+#    needs: [ deploy_aks ]
+    if: ${{ inputs.start_consumer == 'true' }}
     steps:
-      - name: start_consumers
+      - name: Set Subscription Key
         run: |
-          echo "SUBKEY=${{secrets.DEV_SUBKEY}}" >> $GITHUB_ENV 
-          
-          if [[ ${{ inputs.environment }} == "uat" ]]; then
-            echo "SUBKEY=${{secrets.UAT_SUBKEY}}" >> $GITHUB_ENV 
+          if [[ "${{ inputs.environment }}" == "uat" ]]; then
+            echo "SUBKEY=${{ secrets.UAT_SUBKEY }}" >> $GITHUB_ENV
+          else
+            echo "SUBKEY=${{ secrets.DEV_SUBKEY }}" >> $GITHUB_ENV
           fi
 
+      - name: Call START_CONSUMER event
+        run: |
           curl --location --request POST 'https://api.dev.platform.pagopa.it/gpd-rtp/v1/events/publish/START_CONSUMER' \
-            --header 'Ocp-Apim-Subscription-Key: ${{ env.SUBKEY }}'
+            --header "Ocp-Apim-Subscription-Key: $SUBKEY"
 
   notify:
     needs: [ setup, release, deploy_aks ]
